"""ANAL-10 — Per-candidate markdown report generator.

Writes one ``.md`` per ticker into ``output/reports_{timestamp}/{TICKER}.md``
combining:
  - quant scores (combined + 8 base parent scores from factor_scores_parent)
  - Claude analyzer outputs (filing, risk, insider) from analysis_results
  - upcoming earnings catalysts from Phase 1's earnings_calendar
  - red/green flags from filing analyzer + new_risks from risk analyzer
  - sector outlook + top long/short ideas from sector analyzer

Reports are intentionally human-readable, not for downstream parsing — Phase 9
reporting builds its own structured outputs.
"""

from __future__ import annotations

import json
import sqlite3
import time
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Any

import pandas as pd
import structlog

log = structlog.get_logger(__name__)


def write_reports(
    conn: sqlite3.Connection,
    *,
    asof: date,
    tickers: list[str],
    output_dir: Path | None = None,
) -> Path:
    """Write one report per ticker. Returns the directory written to.

    Directory naming: ``output/reports_{YYYYMMDDTHHMMSS}/`` per ANAL-10 spec.
    """
    if output_dir is None:
        ts = datetime.now(tz=UTC).strftime("%Y%m%dT%H%M%S")
        output_dir = Path("output") / f"reports_{ts}"
    output_dir.mkdir(parents=True, exist_ok=True)

    for ticker in tickers:
        path = output_dir / f"{ticker}.md"
        path.write_text(_render_report(conn, ticker=ticker, asof=asof), encoding="utf-8")
        log.debug("report_written", ticker=ticker, path=str(path))

    log.info("reports_written", asof=asof.isoformat(), n=len(tickers), dir=str(output_dir))
    return output_dir


def _render_report(conn: sqlite3.Connection, *, ticker: str, asof: date) -> str:
    """Compose one ticker's markdown report."""
    parts: list[str] = []
    sector = _sector_for(conn, ticker)
    parts.append(f"# {ticker} — Meridian Capital Partners Research Note")
    parts.append("")
    parts.append(f"**As-of date**: {asof.isoformat()}")
    if sector:
        parts.append(f"**GICS sector**: {sector}")
    parts.append(f"**Generated**: {datetime.now(tz=UTC).isoformat(timespec='seconds')}")
    parts.append("")

    # ---- quant scores -----
    parts.append("## Quant Scores (sector-percentile, 0-100)")
    parts.append("")
    quant_df = _load_quant_scores(conn, ticker, asof)
    if quant_df.empty:
        parts.append("*No quant scores available for this ticker on the asof date.*")
    else:
        parts.append(quant_df.to_markdown(index=False, floatfmt=",.1f"))
    parts.append("")

    # ---- Claude analyzer outputs -----
    parts.append("## Claude AI Analysis")
    parts.append("")
    for analyzer, label in (
        ("filing", "Filing analyzer (8 quarters of fundamentals)"),
        ("risk", "Risk analyzer (10-K Risk Factors)"),
        ("insider", "Insider analyzer (Form 4, last 90d)"),
    ):
        parts.append(f"### {label}")
        parts.append("")
        result = _load_analyzer_result(conn, analyzer_type=analyzer, ticker=ticker)
        if result is None:
            parts.append(f"*No {analyzer} analysis available.*")
            parts.append("")
            continue
        parts.append(_format_analyzer_section(analyzer, result))
        parts.append("")

    # ---- sector ideas -----
    if sector:
        sector_result = _load_sector_result(conn, sector=sector, asof=asof)
        if sector_result:
            parts.append(f"## Sector Outlook — {sector}")
            parts.append("")
            parts.append(_format_sector_section(sector_result, ticker_focus=ticker))
            parts.append("")

    # ---- upcoming catalysts -----
    parts.append("## Upcoming Catalysts")
    parts.append("")
    catalysts = _load_catalysts(conn, ticker=ticker, asof=asof)
    if catalysts.empty:
        parts.append("*No earnings dates within the next 30 days.*")
    else:
        parts.append(catalysts.to_markdown(index=False))
    parts.append("")

    parts.append("---")
    parts.append(
        "*Generated by Meridian Capital Partners — automated research desk. "
        "Not investment advice; for internal use only.*"
    )
    return "\n".join(parts)


# --- DB helpers ----------------------------------------------------------


def _sector_for(conn: sqlite3.Connection, ticker: str) -> str | None:
    cur = conn.execute("SELECT sector FROM universe WHERE ticker = ?", (ticker,))
    row = cur.fetchone()
    return row[0] if row else None


def _load_quant_scores(conn: sqlite3.Connection, ticker: str, asof: date) -> pd.DataFrame:
    sql = """
        SELECT factor, parent_score AS score, n_subfactors_used
        FROM factor_scores_parent
        WHERE ticker = ? AND score_date = ?
        ORDER BY
          CASE factor
            WHEN 'combined' THEN 0
            WHEN 'momentum' THEN 1
            WHEN 'value' THEN 2
            WHEN 'quality' THEN 3
            WHEN 'growth' THEN 4
            WHEN 'revisions' THEN 5
            WHEN 'short_interest' THEN 6
            WHEN 'insider' THEN 7
            WHEN 'institutional' THEN 8
            ELSE 9
          END
    """
    return pd.read_sql_query(sql, conn, params=(ticker, asof.isoformat()))


def _load_analyzer_result(
    conn: sqlite3.Connection, *, analyzer_type: str, ticker: str
) -> dict[str, Any] | None:
    cur = conn.execute(
        """
        SELECT response_json FROM analysis_results
        WHERE analyzer_type = ? AND ticker = ? AND expires_at >= ?
        ORDER BY computed_at DESC LIMIT 1
        """,
        (analyzer_type, ticker, int(time.time())),
    )
    row = cur.fetchone()
    if row is None:
        return None
    try:
        return json.loads(row[0])  # type: ignore[no-any-return]
    except (TypeError, json.JSONDecodeError):
        return None


def _load_sector_result(
    conn: sqlite3.Connection, *, sector: str, asof: date
) -> dict[str, Any] | None:
    cur = conn.execute(
        """
        SELECT response_json FROM analysis_results
        WHERE analyzer_type = 'sector' AND ticker = '__sector__'
              AND artifact_id = ? AND expires_at >= ?
        ORDER BY computed_at DESC LIMIT 1
        """,
        (f"sector-{sector}-{asof.isoformat()}", int(time.time())),
    )
    row = cur.fetchone()
    if row is None:
        return None
    try:
        return json.loads(row[0])  # type: ignore[no-any-return]
    except (TypeError, json.JSONDecodeError):
        return None


def _load_catalysts(conn: sqlite3.Connection, *, ticker: str, asof: date) -> pd.DataFrame:
    """Earnings dates from Phase 1's ``earnings_calendar`` within next 30d."""
    sql = """
        SELECT earnings_date, fiscal_period, eps_estimate
        FROM earnings_calendar
        WHERE ticker = ?
          AND earnings_date BETWEEN ? AND date(?, '+30 days')
        ORDER BY earnings_date ASC
    """
    return pd.read_sql_query(sql, conn, params=(ticker, asof.isoformat(), asof.isoformat()))


# --- analyzer-specific formatters ---------------------------------------


def _format_analyzer_section(analyzer: str, result: dict[str, Any]) -> str:
    """Per-analyzer markdown rendering."""
    if analyzer == "filing":
        return _format_filing(result)
    if analyzer == "risk":
        return _format_risk(result)
    if analyzer == "insider":
        return _format_insider(result)
    return f"```json\n{json.dumps(result, indent=2)}\n```"


def _format_filing(r: dict[str, Any]) -> str:
    lines = [
        f"- **Earnings quality**: {r.get('earnings_quality_score', '—')}",
        f"- **Revenue quality**: {r.get('revenue_quality_score', '—')}",
        f"- **Balance sheet**: {r.get('balance_sheet_score', '—')}",
        f"- **Accruals**: {r.get('accruals_score', '—')}",
        f"- **Risk level**: `{r.get('risk_level', '—')}`",
        "",
    ]
    red = r.get("red_flags") or []
    if red:
        lines.append("**Red flags**:")
        lines.extend(f"  - {flag}" for flag in red)
        lines.append("")
    green = r.get("green_flags") or []
    if green:
        lines.append("**Green flags**:")
        lines.extend(f"  - {flag}" for flag in green)
        lines.append("")
    summary = r.get("one_line_summary")
    if summary:
        lines.append(f"> {summary}")
    return "\n".join(lines)


def _format_risk(r: dict[str, Any]) -> str:
    lines = [
        f"- **Severity**: `{r.get('risk_severity', '—')}`",
        f"- **Boilerplate %**: {r.get('boilerplate_percentage', '—')}",
        "",
    ]
    new = r.get("new_risks") or []
    if new:
        lines.append("**New risks vs prior 10-K**:")
        lines.extend(f"  - {risk}" for risk in new)
        lines.append("")
    material = r.get("material_risks") or []
    if material:
        lines.append("**Material risks**:")
        lines.extend(f"  - {risk}" for risk in material)
        lines.append("")
    summary = r.get("one_line_summary")
    if summary:
        lines.append(f"> {summary}")
    return "\n".join(lines)


def _format_insider(r: dict[str, Any]) -> str:
    lines = [
        f"- **Signal**: `{r.get('signal', 'NEUTRAL')}`  ({r.get('confidence', 0.0):.2f} confidence)",
        "",
    ]
    reasoning = r.get("reasoning")
    if reasoning:
        lines.append(reasoning)
        lines.append("")
    txns = r.get("key_transactions") or []
    if txns:
        lines.append("**Key transactions**:")
        for t in txns[:8]:
            lines.append(
                f"  - {t.get('date', '?')}  {t.get('insider', '?')} "
                f"({t.get('title', '?')}) — {t.get('code', '?')} "
                f"{t.get('shares', '?'):,} sh @ ${t.get('value_usd', 0):,.0f}"
            )
        lines.append("")
    summary = r.get("one_line_summary")
    if summary:
        lines.append(f"> {summary}")
    return "\n".join(lines)


def _format_sector_section(r: dict[str, Any], *, ticker_focus: str) -> str:
    """Sector-level idea + outlook. Highlights when ticker_focus matches the
    long or short pick — useful for the per-candidate report."""
    lines = [
        f"- **Stance**: `{r.get('outlook_stance', 'neutral')}`",
        "",
    ]
    long_idea = r.get("top_long_idea") or {}
    short_idea = r.get("top_short_idea") or {}
    if long_idea.get("ticker"):
        marker = "  ← (this ticker)" if long_idea["ticker"] == ticker_focus else ""
        lines.append(f"**Top long**: `{long_idea['ticker']}`{marker}")
        if long_idea.get("thesis"):
            lines.append(long_idea["thesis"])
        lines.append("")
    if short_idea.get("ticker"):
        marker = "  ← (this ticker)" if short_idea["ticker"] == ticker_focus else ""
        lines.append(f"**Top short**: `{short_idea['ticker']}`{marker}")
        if short_idea.get("thesis"):
            lines.append(short_idea["thesis"])
        lines.append("")
    outlook = r.get("sector_outlook")
    if outlook:
        lines.append("**Outlook**:")
        lines.append(outlook)
    return "\n".join(lines)


__all__ = ["write_reports"]
